import { annotate } from './annotate';

import _alpha from './alpha';
import _alphanumeric from './alphanumeric';
import _base64 from './base64';
import _bic from './bic';
import _bytes from './bytes';
import _cc from './cc';
import _cuid from './cuid';
import _cuid2 from './cuid2';
import _date from './date-constraint';
import _dateString from './date-string';
import _domain from './domain';
import _email from './email';
import _emoji from './emoji';
import _endsWith from './ends-with';
import _epoch from './epoch';
import _excludes from './excludes';
import _finite from './finite';
import _graphemes from './graphemes';
import _hash from './hash';
import _hex from './hex';
import _hostname from './hostname';
import _imei from './imei';
import _includes from './includes-str';
import _integer from './integer';
import _ip from './ip';
import _isbn from './isbn';
import _iso from './iso';
import _jsonString from './json-string';
import _jwt from './jwt';
import _length from './length';
import _mac from './mac';
import _matches from './matches';
import _max from './max';
import _mime from './mime';
import _min from './min';
import _multipleOf from './multiple-of';
import _nanoid from './nanoid';
import _negative from './negative';
import _nonNegative from './non-negative';
import _nonPositive from './non-positive';
import _normalize from './normalize';
import _numeric from './numeric';
import _octal from './octal';
import _phone from './phone';
import _positive from './positive';
import _range from './range';
import _safeInteger from './safe-integer';
import _semver from './semver';
import _slug from './slug';
import _startsWith from './starts-with';
import _ulid from './ulid';
import _unique from './unique';
import _url from './url';
import _uuid from './uuid';
import _words from './words';


export { fn } from './annotate';

export const alpha = annotate(_alpha);
export const alphanumeric = annotate(_alphanumeric);
export const base64 = annotate(_base64);
export const bic = annotate(_bic);
export const bytes = annotate(_bytes);
export const cc = annotate(_cc);
export const cuid = annotate(_cuid);
export const cuid2 = annotate(_cuid2);
export const date = annotate(_date);
export const dateString = annotate(_dateString);
export const domain = annotate(_domain);
export const email = annotate(_email);
export const emoji = annotate(_emoji);
export const endsWith = annotate(_endsWith);
export const epoch = annotate(_epoch);
export const excludes = annotate(_excludes);
export const finite = annotate(_finite);
export const graphemes = annotate(_graphemes);
export const hash = annotate(_hash);
export const hex = annotate(_hex);
export const hostname = annotate(_hostname);
export const imei = annotate(_imei);
export const includes = annotate(_includes);
export const integer = annotate(_integer);
export const ip = annotate(_ip);
export const isbn = annotate(_isbn);
export const iso = annotate(_iso);
export const jsonString = annotate(_jsonString);
export const jwt = annotate(_jwt);
export const length = annotate(_length);
export const mac = annotate(_mac);
export const matches = annotate(_matches);
export const max = annotate(_max);
export const mime = annotate(_mime);
export const min = annotate(_min);
export const multipleOf = annotate(_multipleOf);
export const nanoid = annotate(_nanoid);
export const negative = annotate(_negative);
export const nonNegative = annotate(_nonNegative);
export const nonPositive = annotate(_nonPositive);
export const normalize = annotate(_normalize);
export const numeric = annotate(_numeric);
export const octal = annotate(_octal);
export const phone = annotate(_phone);
export const positive = annotate(_positive);
export const range = annotate(_range);
export const safeInteger = annotate(_safeInteger);
export const semver = annotate(_semver);
export const slug = annotate(_slug);
export const startsWith = annotate(_startsWith);
export const ulid = annotate(_ulid);
export const unique = annotate(_unique);
export const url = annotate(_url);
export const uuid = annotate(_uuid);
export const words = annotate(_words);
